---

- name: Install project dependencies
  hosts: all
  # https://spacelift.io/blog/ansible-variables#how-to-share-and-reuse-ansible-variables
  vars_files: ./vars.yml

  tasks:

  # - name: Get DEB architecture
  #   shell: dpkg --print-architecture
  #   register: deb_architecture

  - name: Install GPG
    tags: nodejs, install, setup
    apt:
      name: gnupg
      update_cache: yes
      state: present

  - name: Install the gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
      state: present

  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: Install NodeJS
    tags: nodesjs, install
    apt:
      name: nodejs
      state: latest

# https://www.closingtags.com/blog/deploying-node-js-apps-with-ansible